//------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using B2XCore.Data;

namespace B2XCore.Data
{
	/// <summary>
	///
	/// </summary>
	partial class B2XCoreDataContext
	{
		#region Member variables

		private readonly IHistoriography _historiography;

		#endregion Member variables

		#region Constructor

		/// <summary>
		/// Initializes a new instance of the <see cref="B2XCoreDataContext"/> class.
		/// </summary>
		/// <param name="historiography">The historiography.</param>
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0")]
		public B2XCoreDataContext(IHistoriography historiography)
			: this(historiography.ConnectionString)
		{
			_historiography = historiography;
		}

		#endregion Constructor

		#region Public properties

		/// <summary>
		/// Gets the historiography.
		/// </summary>
		public IHistoriography Historiography { get { return _historiography; } }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreApplicationHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreClientHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreClientLanguageHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreDomainHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreDomainResourceHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreGroupHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreImplementationHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreInstanceHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreInstanceActivityHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreLanguageHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreMachineHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreResourceHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreResourceResourceValueHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreResourceValueHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreSettingHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreSettingDefinitionHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreTimeZoneHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreUserHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreUserDomainResourceHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreUserGroupHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreUserPropertyHistoriography { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether to skip historiography for this table.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if skip historiography; otherwise, <c>false</c>.
		/// </value>
		public bool SkipB2XCoreUserPropertyDefinitionHistoriography { get; set; }

		#endregion Public properties

		#region Private methods

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreApplication(B2XCoreApplication instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreApplicationHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreApplication(B2XCoreApplication instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreApplicationHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreClient(B2XCoreClient instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreClientHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreClient(B2XCoreClient instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreClientHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreClientLanguage(B2XCoreClientLanguage instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreClientLanguageHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreClientLanguage(B2XCoreClientLanguage instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreClientLanguageHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreDomain(B2XCoreDomain instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreDomainHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreDomain(B2XCoreDomain instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreDomainHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreDomainResource(B2XCoreDomainResource instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreDomainResourceHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreDomainResource(B2XCoreDomainResource instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreDomainResourceHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreGroup(B2XCoreGroup instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreGroupHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreGroup(B2XCoreGroup instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreGroupHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreImplementation(B2XCoreImplementation instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreImplementationHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreImplementation(B2XCoreImplementation instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreImplementationHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreInstance(B2XCoreInstance instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreInstanceHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreInstance(B2XCoreInstance instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreInstanceHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreInstanceActivity(B2XCoreInstanceActivity instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreInstanceActivityHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreInstanceActivity(B2XCoreInstanceActivity instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreInstanceActivityHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreLanguage(B2XCoreLanguage instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreLanguageHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreLanguage(B2XCoreLanguage instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreLanguageHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreMachine(B2XCoreMachine instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreMachineHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreMachine(B2XCoreMachine instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreMachineHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreResource(B2XCoreResource instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreResourceHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreResource(B2XCoreResource instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreResourceHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreResourceResourceValue(B2XCoreResourceResourceValue instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreResourceResourceValueHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreResourceResourceValue(B2XCoreResourceResourceValue instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreResourceResourceValueHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreResourceValue(B2XCoreResourceValue instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreResourceValueHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreResourceValue(B2XCoreResourceValue instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreResourceValueHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreSetting(B2XCoreSetting instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreSettingHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreSetting(B2XCoreSetting instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreSettingHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreSettingDefinition(B2XCoreSettingDefinition instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreSettingDefinitionHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreSettingDefinition(B2XCoreSettingDefinition instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreSettingDefinitionHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreTimeZone(B2XCoreTimeZone instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreTimeZoneHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreTimeZone(B2XCoreTimeZone instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreTimeZoneHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreUser(B2XCoreUser instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreUserHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreUser(B2XCoreUser instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreUserHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreUserDomainResource(B2XCoreUserDomainResource instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreUserDomainResourceHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreUserDomainResource(B2XCoreUserDomainResource instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreUserDomainResourceHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreUserGroup(B2XCoreUserGroup instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreUserGroupHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreUserGroup(B2XCoreUserGroup instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreUserGroupHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreUserProperty(B2XCoreUserProperty instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreUserPropertyHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreUserProperty(B2XCoreUserProperty instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreUserPropertyHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void UpdateB2XCoreUserPropertyDefinition(B2XCoreUserPropertyDefinition instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreUserPropertyDefinitionHistoriography)
				_historiography.Update(instance);

			ExecuteDynamicUpdate(instance);
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		partial void DeleteB2XCoreUserPropertyDefinition(B2XCoreUserPropertyDefinition instance)
		{
			if (_historiography != null &&
				!SkipB2XCoreUserPropertyDefinitionHistoriography)
				_historiography.Delete(instance);

			ExecuteDynamicDelete(instance);
		}

		#endregion Private methods
	}
}
