//------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2XCore.Types
{
	/// <summary>
	/// Container for product informations.
	/// </summary>
	public sealed class Product
	{
		#region Constructor

		/// <summary>
		/// Prevents initializing a new instance of the <see cref="Product"/> class.
		/// </summary>
		private Product()
		{
		}

		#endregion Constructor

		#region Constants

		/// <summary>
		/// Copyright for the application.
		/// </summary>
		public const string Copyright = "Copyright © 2017 Dirk Helbig";

		/// <summary>
		/// Name of the application.
		/// </summary>
		public const string Name = "B2XCore";

		/// <summary>
		/// File version of the application.
		/// </summary>
		internal const string FileVersion = "1.2.17950";

		/// <summary>
		/// Version of the application.
		/// </summary>
		internal const string Version = "1.2.17950.17950";

		#endregion Constants
	}
}